<?php
/**
 * Credorax Payments For Magento 2
 * https://www.credorax.com/
 *
 * @category Credorax
 * @package  Credorax_Credorax
 * @author   Girit-Interactive (https://www.girit-tech.com/)
 *
 *
 * @var Credorax\Credorax\Block\Payment\Fingerprint $block
 */
?>
<form id="credorax_fingerprint_form" action="<?php /* @noEscape */ echo $block->getThreeDSMethodUrl(); ?>" method="POST">
    <input type="text" name="threeDSMethodData" value="<?php /* @noEscape */ echo $block->getThreeDSMethodData(); ?>">
</form>
<script>
    window.onload = function(){
        parent.credorax_fingerprint_form_submitted = Date.now() + 10000;
        document.getElementById('credorax_fingerprint_form').submit();
    }
</script>
