<?php
/**
 * Shift4 Payments For Magento 2
 * https://www.shift4.com/
 *
 * @category Shift4
 * @package  Shift4_Shift4
 * @author   Girit-Interactive (https://www.girit-tech.com/)
 *
 *
 * @var Shift4\Shift4\Block\Payment\Fingerprint $block
 */
?>
<form id="shift4_fingerprint_form" action="<?php /* @noEscape */ echo $block->getThreeDSMethodUrl(); ?>" method="POST">
    <input type="text" name="threeDSMethodData" value="<?php /* @noEscape */ echo $block->getThreeDSMethodData(); ?>">
</form>
<script>
    window.onload = function(){
        parent.shift4_fingerprint_form_submitted = Date.now() + 10000;
        document.getElementById('shift4_fingerprint_form').submit();
    }
</script>
