<?php
/**
 * @var Credorax\Credorax\Block\Payment\Fingerprint $block
 */
?>
<form id="credorax_fingerprint_form" action="<?php /* @noEscape */ echo $block->getThreeDSMethodUrl(); ?>" method="POST">
    <input type="text" name="threeDSMethodData" value="<?php /* @noEscape */ echo $block->getThreeDSMethodData(); ?>">
</form>
<script>
    window.onload = function(){
        parent.credorax_fingerprint_form_submitted = Date.now() + 10000;
        document.getElementById('credorax_fingerprint_form').submit();
    }
</script>
