<?php
/**
 * @var Credorax\Credorax\Block\Payment\Authenticate\Form $block
 */
?>
<form name="credorax_authenticate"
      id="credorax_authenticate"
      action="<?php /* @noEscape */ echo $block->getAscUrl(); ?>"
      method="POST">
    <input type="hidden" name="PaReq" value="<?php /* @noEscape */ echo $block->getPaReq(); ?>">
    <input type="hidden" name="TermUrl" value="<?php /* @noEscape */ echo $block->getTermUrl(); ?>">
</form>